language: objective-c

before_install:
    - gem install cocoapods
      - pod install

      script:
          - xctool TransitionUtil.xcodeproj -scheme TransitionUtil -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
